### PR TITLE
Check that batch size matches the target size in ClassNLLCriterion

### PR DESCRIPTION
**Pull request by apaszke**

### CODE REVIEW

**Comment by soumith** [comment]
thanks!

**Comment by JoostvDoorn** [comment]
This pull request breaks the single target CrossEntropy in cuda.

See:
```lua
require 'cunn'
criterion = nn.CrossEntropyCriterion():cuda()
criterion:forward(torch.Tensor(3, 40):cuda(), torch.Tensor{1,1,1}:cuda())
criterion:forward(torch.Tensor(1, 40):cuda(), torch.Tensor{1}:cuda())
```

The test ClassNLLCriterionSingleTarget was already broken before this pull request.

**Comment by soumith** [comment]
@JoostvDoorn thanks. this surfaced a bug in nn, i fixed it via https://github.com/torch/nn/commit/3b8e5a8064b4d359ab691369ace524c9b5b87575

**Comment by JoostvDoorn** [comment]
Great thanks!

**Pull request merged**
