### PR TITLE
Convert real to accreal in libTHCUNN

### PR DESCRIPTION
**Pull request by pavanky**
- This reverts commit 0d85922d116879448485ef88ae21e83a9255a0b0.
- Includes fixes for TemporalRowConvolution

### CODE REVIEW

**Comment by fredowski** [comment]
Issue #380 should be reopened as it currently still a problem in master. History:

- A  Patch proposed in Pull Request #416 which was merged.
- The patch was reversed with Pull Request #427 (merged).
- This Pull Request #442 seems to be "similar" (equal?) to the original #416.

**Comment by pavanky** [comment]
@fredowski #427 happened because @soumith and @deepcoord was seeing failures on their machines. After failing to reproduce this on my end, and discussing over email, I was asked to resend the PR. So this issue is just a revert of #427 with a small additional change.

**Comment by fredowski** [comment]
@pavanky I tested your cunn pull request from https://github.com/twitter-forks/cunn.git 

So I cloned your repo in a separate cunn directory and run 
`luarocks make rocks/cunn-scm-1.rockspec`

My test results are:

```
beckmanf@breakout:~/torch$ th -lcunn -e "nn.testcuda()"
seed: 	73714354	
Running 172 tests
  1/172 TemporalConvolution_backward_batch .............................. [PASS]
  2/172 SpatialAveragePooling_backward .................................. [PASS]
  3/172 ClassNLLCriterionSingleTargetWeights ............................ [PASS]
  4/172 VolumetricDilatedMaxPooling_backward_batch ...................... [PASS]
  5/172 SpatialAdaptiveMaxPooling_forward ............................... [PASS]
  6/172 VolumetricFullConvolution_pair_test ............................. [PASS]
  7/172 SpatialConvolutionMM_backward_batch ............................. [PASS]
  8/172 VolumetricConvolution_forward_single ............................ [PASS]
  9/172 RReLU_backward .................................................. [PASS]
 10/172 SpatialDilatedConvolution_forward_single ........................ [PASS]
 11/172 PReLU_backward .................................................. [PASS]
 12/172 Sqrt_zero ....................................................... [PASS]
 13/172 Euclidean_forward_batch ......................................... [PASS]
 14/172 SparseLinear_backward ........................................... [PASS]
 15/172 TemporalConvolution_backward .................................... [PASS]
 16/172 MultiLabelMarginCriterion_backward .............................. [PASS]
 17/172 VolumetricReplicationPadding_backward ........................... [PASS]
 18/172 SoftShrink_forward .............................................. [PASS]
 19/172 ELU_transposed .................................................. [PASS]
 20/172 SpatialConvolutionMM_backward_single ............................ [PASS]
 21/172 VolumetricDilatedConvolution .................................... [PASS]
 22/172 GPU ............................................................. [PASS]
 23/172 BCECriterionWeights_forward ..................................... [PASS]
 24/172 SpatialDilatedMaxPooling_forward_batch .......................... [PASS]
 25/172 SpatialConvolutionLocal_backward_batch .......................... [PASS]
 26/172 Sqrt_backward ................................................... [PASS]
 27/172 Abs_backward .................................................... [PASS]
 28/172 Dropout_forward ................................................. [PASS]
 29/172 Sigmoid_backward ................................................ [PASS]
 30/172 VolumetricMaxUnpooling_backward_batch ........................... [PASS]
 31/172 SpatialFractionalMaxPooling_backward ............................ [PASS]
 32/172 HardTanh_backward_inplace ....................................... [PASS]
 33/172 Sigmoid_forward ................................................. [PASS]
 34/172 Square_forward .................................................. [PASS]
 35/172 SpatialClassNLLCriterion ........................................ [PASS]
 36/172 SpatialConvolutionLocal_forward_single .......................... [PASS]
 37/172 VolumetricMaxUnpooling_forward_batch ............................ [PASS]
 38/172 Abs_forward ..................................................... [PASS]
 39/172 PReLU_forward ................................................... [PASS]
 40/172 MarginCriterion_backward ........................................ [PASS]
 41/172 Sqrt_transposed ................................................. [PASS]
 42/172 SpatialDilatedConvolution_forward_batch ......................... [PASS]
 43/172 BCECriterion_backward ........................................... [PASS]
 44/172 Tanh_forward .................................................... [PASS]
 45/172 LeakyReLU_forward ............................................... [PASS]
 46/172 SpatialReplicationPadding_backward .............................. [PASS]
 47/172 SpatialAdaptiveMaxPooling_forward_noncontig ..................... [PASS]
 48/172 LogSoftMax_forward_batch ........................................ [PASS]
 49/172 ELU_forward ..................................................... [PASS]
 50/172 SparseLinear_forward ............................................ [PASS]
 51/172 SpatialLogSoftMax_backward_batch ................................ [PASS]
 52/172 SoftMax_backward ................................................ [PASS]
 53/172 SpatialUpSamplingNearest_forward ................................ [PASS]
 54/172 SpatialAdaptiveMaxPooling_backward .............................. [PASS]
 55/172 SoftMax_forward ................................................. [PASS]
 56/172 SpatialUpSamplingBilinear_backward_batch ........................ [PASS]
 57/172 SpatialUpSamplingNearest_backward ............................... [PASS]
 58/172 Square_backward ................................................. [PASS]
 59/172 LeakyReLU_transposed ............................................ [PASS]
 60/172 LogSoftMax_backward ............................................. [PASS]
 61/172 LeakyReLU_backward .............................................. [PASS]
 62/172 SpatialConvolutionMM_forward_single ............................. [PASS]
 63/172 VolumetricFullConvolution ....................................... [PASS]
 64/172 VolumetricReplicationPadding_forward ............................ [PASS]
 65/172 SoftMarginCriterion ............................................. [PASS]
 66/172 SpatialUpSamplingBilinear_forward ............................... [PASS]
 67/172 HardTanh_forward ................................................ [PASS]
 68/172 Euclidean_backward_batch ........................................ [PASS]
 69/172 SpatialAveragePooling_forward_batch ............................. [PASS]
 70/172 SpatialAveragePooling_backward_batch ............................ [PASS]
 71/172 SpatialLogSoftMax_backward ...................................... [PASS]
 72/172 SpatialMaxPooling_backward ...................................... [PASS]
 73/172 TemporalConvolution_forward ..................................... [PASS]
 74/172 SpatialAdaptiveMaxPooling_backward_batch ........................ [PASS]
 75/172 TemporalMaxPooling .............................................. [PASS]
 76/172 VolumetricAveragePooling_backward ............................... [PASS]
 77/172 HardTanh_transposed ............................................. [PASS]
 78/172 Threshold_forward ............................................... [PASS]
 79/172 SpatialBatchNormalization ....................................... [PASS]
 80/172 MultiLabelMarginCriterion_forward ............................... [PASS]
 81/172 BatchNormalization .............................................. [PASS]
 82/172 LogSigmoid_forward .............................................. [PASS]
 83/172 SpatialAdaptiveMaxPooling_forward_batch ......................... [PASS]
 84/172 SpatialCrossMapLRN_forward_batch ................................ [PASS]
 85/172 SoftShrink_backward ............................................. [PASS]
 86/172 SpatialFullConvolution_forward_single ........................... [PASS]
 87/172 TemporalConvolution_forward_batch ............................... [PASS]
 88/172 SpatialCrossMapLRN_backward_batch ............................... [PASS]
 89/172 SoftPlus_forward ................................................ [PASS]
 90/172 IndexLinear ..................................................... [ERROR]
 91/172 SpatialSoftMax .................................................. [PASS]
 92/172 SpatialReplicationPadding_forward ............................... [PASS]
 93/172 SpatialFractionalMaxPooling_forward ............................. [PASS]
 94/172 LogSigmoid_backward ............................................. [PASS]
 95/172 ReLU6_backward .................................................. [PASS]
 96/172 SpatialSubSampling_forward ...................................... [PASS]
 97/172 IndexLinearMaxNorm .............................................. [ERROR]
 98/172 SpatialReflectionPadding_forward ................................ [PASS]
 99/172 BCECriterion_forward ............................................ [PASS]
100/172 SpatialMaxPooling_forward_batch ................................. [PASS]
101/172 SpatialDilatedMaxPooling_backward ............................... [PASS]
102/172 SpatialSubSampling_backward_batch ............................... [PASS]
103/172 LogSoftMax_forward .............................................. [PASS]
104/172 SpatialDilatedConvolution_backward_single ....................... [PASS]
105/172 SpatialAveragePooling_forward ................................... [PASS]
106/172 SpatialMaxUnpooling_forward_batch ............................... [PASS]
107/172 mse ............................................................. [FAIL]
108/172 VolumetricMaxPooling_forward .................................... [PASS]
109/172 LookupTable_backward ............................................ [PASS]
110/172 CMul_backward_batch ............................................. [PASS]
111/172 LookupTable_forward ............................................. [PASS]
112/172 HardTanh_backward ............................................... [PASS]
113/172 Square_transposed ............................................... [PASS]
114/172 Threshold_backward .............................................. [PASS]
115/172 Sigmoid_transposed .............................................. [PASS]
116/172 VolumetricConvolution_backward_batch ............................ [PASS]
117/172 SpatialAdaptiveMaxPooling_backward_noncontig .................... [PASS]
118/172 SpatialMaxPooling_forward ....................................... [PASS]
119/172 SpatialConvolutionLocal_forward_batch ........................... [PASS]
120/172 CMul_forward_batch .............................................. [PASS]
121/172 VolumetricDilatedMaxPooling_forward_batch ....................... [PASS]
122/172 ELU_backward .................................................... [PASS]
123/172 SpatialLPPooling_forward ........................................ [PASS]
124/172 SpatialMaxPooling_backward_batch ................................ [PASS]
125/172 Sampling_forward_batch .......................................... [PASS]
126/172 SpatialLPPooling_backward ....................................... [PASS]
127/172 SpatialFullConvolution_backward_single .......................... [PASS]
128/172 ClassNLLCriterionMultipleTarget ................................. [PASS]
129/172 SpatialLogSoftMax_forward_batch ................................. [PASS]
130/172 SmoothL1 ........................................................ [FAIL]
131/172 BCECriterionWeights_backward .................................... [PASS]
132/172 SpatialDilatedMaxPooling_forward ................................ [PASS]
133/172 SpatialUpSamplingBilinear_forward_batch ......................... [PASS]
134/172 SpatialFullConvolution_backward_batch ........................... [PASS]
135/172 SpatialUpSamplingNearest_backward_batch ......................... [PASS]
136/172 SpatialConvolutionLocal_backward_single ......................... [PASS]
137/172 VolumetricBatchNormalization .................................... [PASS]
138/172 SpatialDilatedMaxPooling_backward_batch ......................... [PASS]
139/172 VolumetricConvolution_forward_batch ............................. [PASS]
140/172 Tanh_backward ................................................... [PASS]
141/172 WeightedEuclidean_backward_batch ................................ [PASS]
142/172 SoftPlus_backward ............................................... [PASS]
143/172 getParameters ................................................... [PASS]
144/172 LogSigmoid_transposed ........................................... [PASS]
145/172 SpatialConvolutionMM_forward_batch .............................. [PASS]
146/172 SpatialSubSampling_backward ..................................... [PASS]
147/172 SpatialUpSamplingNearest_forward_batch .......................... [PASS]
148/172 ReLU6_forward ................................................... [PASS]
149/172 SpatialMaxUnpooling_backward_batch .............................. [PASS]
150/172 ClassNLLCriterionSingleTarget ................................... [PASS]
151/172 MarginCriterion_forward ......................................... [PASS]
152/172 Tanh_transposed ................................................. [PASS]
153/172 ClassNLLCriterionMultipleTargetWeights .......................... [PASS]
154/172 VolumetricAveragePooling_forward ................................ [PASS]
155/172 distkldiv ....................................................... [PASS]
156/172 Dropout ......................................................... [PASS]
157/172 SpatialAveragePooling_includepad ................................ [PASS]
158/172 WeightedEuclidean_forward_batch ................................. [PASS]
159/172 SpatialDilatedConvolution_backward_batch ........................ [PASS]
160/172 VolumetricMaxPooling_backward ................................... [PASS]
161/172 SpatialUpSamplingBilinear_backward .............................. [PASS]
162/172 VolumetricConvolution_backward_single ........................... [PASS]
163/172 SpatialFullConvolution_forward_batch ............................ [PASS]
164/172 Abs_transposed .................................................. [PASS]
165/172 RReLU_forward ................................................... [PASS]
166/172 SpatialLogSoftMax_forward ....................................... [PASS]
167/172 Sqrt_forward .................................................... [PASS]
168/172 SpatialReflectionPadding_backward ............................... [PASS]
169/172 l1cost .......................................................... [FAIL]
170/172 SoftShrink_transposed ........................................... [PASS]
171/172 ModuleConversionFunctions ....................................... [PASS]
172/172 LogSoftMax_backward_batch ....................................... [PASS]
Completed 2193 asserts in 172 tests with 3 failures and 2 errors
--------------------------------------------------------------------------------
IndexLinear
 Function call failed
/rz2home/beckmanf/torch/install/share/lua/5.2/cunn/test.lua:5468: attempt to call field 'IndexLinear' (a nil value)
stack traceback:
	/rz2home/beckmanf/torch/install/share/lua/5.2/cunn/test.lua:5468: in function 'v'
	/rz2home/beckmanf/torch/install/share/lua/5.2/cunn/test.lua:5898: in function </rz2home/beckmanf/torch/install/share/lua/5.2/cunn/test.lua:5896>
	[C]: in function 'xpcall'
	...me/beckmanf/torch/install/share/lua/5.2/torch/Tester.lua:477: in function '_pcall'
	...me/beckmanf/torch/install/share/lua/5.2/torch/Tester.lua:436: in function '_run'
	...me/beckmanf/torch/install/share/lua/5.2/torch/Tester.lua:355: in function 'run'
	/rz2home/beckmanf/torch/install/share/lua/5.2/cunn/test.lua:5919: in function 'testcuda'
	[string "nn.testcuda()"]:1: in main chunk
	[C]: in function 'pcall'
	...manf/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:136: in main chunk
	[C]: in ?

--------------------------------------------------------------------------------
IndexLinearMaxNorm
 Function call failed
/rz2home/beckmanf/torch/install/share/lua/5.2/cunn/test.lua:5630: attempt to call field 'IndexLinear' (a nil value)
stack traceback:
	/rz2home/beckmanf/torch/install/share/lua/5.2/cunn/test.lua:5630: in function 'v'
	/rz2home/beckmanf/torch/install/share/lua/5.2/cunn/test.lua:5898: in function </rz2home/beckmanf/torch/install/share/lua/5.2/cunn/test.lua:5896>
	[C]: in function 'xpcall'
	...me/beckmanf/torch/install/share/lua/5.2/torch/Tester.lua:477: in function '_pcall'
	...me/beckmanf/torch/install/share/lua/5.2/torch/Tester.lua:436: in function '_run'
	...me/beckmanf/torch/install/share/lua/5.2/torch/Tester.lua:355: in function 'run'
	/rz2home/beckmanf/torch/install/share/lua/5.2/cunn/test.lua:5919: in function 'testcuda'
	[string "nn.testcuda()"]:1: in main chunk
	[C]: in function 'pcall'
	...manf/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:136: in main chunk
	[C]: in ?

--------------------------------------------------------------------------------
mse
error  on output with torch.CudaHalfTensor
LT failed: 2.908203125 >= 0.03
	/rz2home/beckmanf/torch/install/share/lua/5.2/cunn/test.lua:3401: in function 'v'
	/rz2home/beckmanf/torch/install/share/lua/5.2/cunn/test.lua:5898: in function </rz2home/beckmanf/torch/install/share/lua/5.2/cunn/test.lua:5896>
--------------------------------------------------------------------------------
SmoothL1
error  on output with torch.CudaHalfTensor
LT failed: 0.584716796875 >= 0.01
	/rz2home/beckmanf/torch/install/share/lua/5.2/cunn/test.lua:3432: in function 'v'
	/rz2home/beckmanf/torch/install/share/lua/5.2/cunn/test.lua:5898: in function </rz2home/beckmanf/torch/install/share/lua/5.2/cunn/test.lua:5896>
--------------------------------------------------------------------------------
l1cost
error  on output with torch.CudaHalfTensor
LT failed: 0.10342407226562 >= 0.0101
	/rz2home/beckmanf/torch/install/share/lua/5.2/cunn/test.lua:3994: in function 'v'
	/rz2home/beckmanf/torch/install/share/lua/5.2/cunn/test.lua:5898: in function </rz2home/beckmanf/torch/install/share/lua/5.2/cunn/test.lua:5896>
--------------------------------------------------------------------------------
...me/beckmanf/torch/install/share/lua/5.2/torch/Tester.lua:363: An error was found while running tests!	
beckmanf@breakout:~/torch$ 
```

So there are the mse, l1cost and SmoothL1 errors which seem to be related to precision problems. Further there are errors with IndexLinear, IndexLinearMaxNorm which were not in the simple revert that I described in issue #380. The warning that I noticed for TemporalRowConvolution disappeared.

**Comment by fredowski** [comment]
Sorry, the previous test was run on the twitter branch and not the half-fixes...

**Comment by fredowski** [comment]
Hi, I tested your Pull Request and see the following test results:

```
beckmanf@breakout:~/cunn$ th -lcunn -e "nn.testcuda()"
seed: 	729466276	
Running 176 tests
  1/176 Abs_transposed .................................................. [PASS]
  2/176 SpatialReflectionPadding_forward ................................ [PASS]
  3/176 GatedLinearUnit_forward ......................................... [PASS]
  4/176 Tanh_forward .................................................... [PASS]
  5/176 LookupTable_backward ............................................ [PASS]
  6/176 SpatialMaxPooling_backward_batch ................................ [PASS]
  7/176 GPU ............................................................. [PASS]
  8/176 SpatialDilatedMaxPooling_forward_batch .......................... [PASS]
  9/176 TemporalRowConvolution_forward_single ........................... [PASS]
 10/176 ReLU6_backward .................................................. [PASS]
 11/176 SpatialReflectionPadding_backward ............................... [PASS]
 12/176 LogSoftMax_backward_batch ....................................... [PASS]
 13/176 SpatialFullConvolution_backward_single .......................... [PASS]
 14/176 VolumetricConvolution_forward_single ............................ [PASS]
 15/176 LogSoftMax_backward ............................................. [PASS]
 16/176 SpatialSubSampling_backward ..................................... [PASS]
 17/176 SparseLinear_backward ........................................... [PASS]
 18/176 Square_forward .................................................. [PASS]
 19/176 RReLU_forward ................................................... [PASS]
 20/176 VolumetricDilatedConvolution .................................... [PASS]
 21/176 BCECriterionWeights_backward .................................... [PASS]
 22/176 PReLU_forward ................................................... [PASS]
 23/176 SpatialCrossMapLRN_backward_batch ............................... [PASS]
 24/176 SpatialFullConvolution_backward_batch ........................... [PASS]
 25/176 SpatialFractionalMaxPooling_backward ............................ [PASS]
 26/176 VolumetricFullConvolution_pair_test ............................. [PASS]
 27/176 ReLU6_forward ................................................... [PASS]
 28/176 HardTanh_forward ................................................ [PASS]
 29/176 BatchNormalization .............................................. [PASS]
 30/176 LogSigmoid_backward ............................................. [PASS]
 31/176 SpatialAdaptiveMaxPooling_forward_batch ......................... [PASS]
 32/176 Sqrt_zero ....................................................... [PASS]
 33/176 VolumetricConvolution_backward_batch ............................ [PASS]
 34/176 Square_transposed ............................................... [PASS]
 35/176 VolumetricFullConvolution ....................................... [PASS]
 36/176 SpatialMaxPooling_forward_batch ................................. [PASS]
 37/176 SpatialSubSampling_backward_batch ............................... [PASS]
 38/176 ELU_forward ..................................................... [PASS]
 39/176 Tanh_transposed ................................................. [PASS]
 40/176 mse ............................................................. [FAIL]
 41/176 MultiLabelMarginCriterion_forward ............................... [PASS]
 42/176 Euclidean_forward_batch ......................................... [PASS]
 43/176 VolumetricBatchNormalization .................................... [PASS]
 44/176 SpatialConvolutionMM_backward_batch ............................. [PASS]
 45/176 SpatialReplicationPadding_backward .............................. [PASS]
 46/176 LogSoftMax_forward_batch ........................................ [PASS]
 47/176 Sigmoid_forward ................................................. [PASS]
 48/176 ELU_backward .................................................... [PASS]
 49/176 VolumetricReplicationPadding_backward ........................... [PASS]
 50/176 SpatialDilatedMaxPooling_backward_batch ......................... [PASS]
 51/176 SpatialUpSamplingBilinear_backward .............................. [PASS]
 52/176 VolumetricConvolution_backward_single ........................... [PASS]
 53/176 ModuleConversionFunctions ....................................... [PASS]
 54/176 SpatialMaxUnpooling_forward_batch ............................... [PASS]
 55/176 HardTanh_backward_inplace ....................................... [PASS]
 56/176 SoftShrink_forward .............................................. [PASS]
 57/176 SpatialDilatedConvolution_backward_single ....................... [PASS]
 58/176 LogSigmoid_forward .............................................. [PASS]
 59/176 VolumetricConvolution_forward_batch ............................. [PASS]
 60/176 SpatialSoftMax .................................................. [PASS]
 61/176 SpatialAdaptiveMaxPooling_forward ............................... [PASS]
 62/176 Euclidean_backward_batch ........................................ [PASS]
 63/176 HardTanh_backward ............................................... [PASS]
 64/176 WeightedEuclidean_forward_batch ................................. [PASS]
 65/176 SpatialFullConvolution_forward_single ........................... [PASS]
 66/176 SoftMarginCriterion ............................................. [PASS]
 67/176 VolumetricDilatedMaxPooling_backward_batch ...................... [PASS]
 68/176 TemporalConvolution_backward_batch .............................. [PASS]
 69/176 RReLU_backward .................................................. [PASS]
 70/176 Sampling_forward_batch .......................................... [PASS]
 71/176 SpatialCrossMapLRN_forward_batch ................................ [PASS]
 72/176 SpatialAdaptiveMaxPooling_backward .............................. [PASS]
 73/176 PReLU_backward .................................................. [PASS]
 74/176 LogSoftMax_forward .............................................. [PASS]
 75/176 LookupTable_forward ............................................. [PASS]
 76/176 Sigmoid_transposed .............................................. [PASS]
 77/176 SpatialAdaptiveMaxPooling_backward_batch ........................ [PASS]
 78/176 SpatialUpSamplingNearest_forward_batch .......................... [PASS]
 79/176 SpatialMaxPooling_forward ....................................... [PASS]
 80/176 SpatialUpSamplingNearest_backward_batch ......................... [PASS]
 81/176 SpatialLogSoftMax_backward_batch ................................ [PASS]
 82/176 SpatialLogSoftMax_backward ...................................... [PASS]
 83/176 Sqrt_backward ................................................... [PASS]
 84/176 SpatialUpSamplingBilinear_forward ............................... [PASS]
 85/176 TemporalMaxPooling .............................................. [PASS]
 86/176 SpatialConvolutionMM_backward_single ............................ [PASS]
 87/176 TemporalRowConvolution_backward_single .......................... [PASS]
 88/176 SpatialClassNLLCriterion ........................................ [PASS]
 89/176 Sigmoid_backward ................................................ [PASS]
 90/176 SpatialDilatedMaxPooling_forward ................................ [PASS]
 91/176 TemporalConvolution_forward_batch ............................... [PASS]
 92/176 SparseLinear_forward ............................................ [PASS]
 93/176 SpatialFractionalMaxPooling_forward ............................. [PASS]
 94/176 SpatialAdaptiveMaxPooling_forward_noncontig ..................... [PASS]
 95/176 SpatialLPPooling_forward ........................................ [PASS]
 96/176 SpatialDilatedConvolution_forward_single ........................ [PASS]
 97/176 Dropout ......................................................... [PASS]
 98/176 SoftPlus_backward ............................................... [PASS]
 99/176 SpatialLPPooling_backward ....................................... [PASS]
100/176 SpatialAveragePooling_backward .................................. [PASS]
101/176 SpatialUpSamplingNearest_forward ................................ [PASS]
102/176 MarginCriterion_backward ........................................ [PASS]
103/176 distkldiv ....................................................... [PASS]
104/176 SpatialDilatedConvolution_backward_batch ........................ [PASS]
105/176 BCECriterion_backward ........................................... [PASS]
106/176 ClassNLLCriterionSingleTarget ................................... [PASS]
107/176 MultiLabelMarginCriterion_backward .............................. [PASS]
108/176 Dropout_forward ................................................. [PASS]
109/176 VolumetricMaxPooling_backward ................................... [PASS]
110/176 SpatialMaxUnpooling_backward_batch .............................. [PASS]
111/176 SoftShrink_transposed ........................................... [PASS]
112/176 SpatialConvolutionLocal_backward_single ......................... [PASS]
113/176 LeakyReLU_transposed ............................................ [PASS]
114/176 SpatialDilatedMaxPooling_backward ............................... [PASS]
115/176 VolumetricReplicationPadding_forward ............................ [PASS]
116/176 VolumetricAveragePooling_forward ................................ [PASS]
117/176 SpatialLogSoftMax_forward_batch ................................. [PASS]
118/176 TemporalConvolution_forward ..................................... [PASS]
119/176 Threshold_forward ............................................... [PASS]
120/176 MarginCriterion_forward ......................................... [PASS]
121/176 SpatialMaxPooling_backward ...................................... [PASS]
122/176 SoftMax_backward ................................................ [PASS]
123/176 Abs_backward .................................................... [PASS]
124/176 SpatialConvolutionLocal_forward_single .......................... [PASS]
125/176 Square_backward ................................................. [PASS]
126/176 LeakyReLU_backward .............................................. [PASS]
127/176 Sqrt_forward .................................................... [PASS]
128/176 BCECriterionWeights_forward ..................................... [PASS]
129/176 VolumetricMaxUnpooling_forward_batch ............................ [PASS]
130/176 HardTanh_transposed ............................................. [PASS]
131/176 getParameters ................................................... [PASS]
132/176 TemporalRowConvolution_backward_batch ........................... [PASS]
133/176 WeightedEuclidean_backward_batch ................................ [PASS]
134/176 ClassNLLCriterionMultipleTarget ................................. [PASS]
135/176 SoftShrink_backward ............................................. [PASS]
136/176 SpatialConvolutionLocal_backward_batch .......................... [PASS]
137/176 SpatialUpSamplingNearest_backward ............................... [PASS]
138/176 ClassNLLCriterionSingleTargetWeights ............................ [PASS]
139/176 Tanh_backward ................................................... [PASS]
140/176 LogSigmoid_transposed ........................................... [PASS]
141/176 CMul_backward_batch ............................................. [PASS]
142/176 GatedLinearUnit_backward ........................................ [PASS]
143/176 SpatialAveragePooling_backward_batch ............................ [PASS]
144/176 TemporalConvolution_backward .................................... [PASS]
145/176 SpatialUpSamplingBilinear_forward_batch ......................... [PASS]
146/176 SoftMax_forward ................................................. [PASS]
147/176 LeakyReLU_forward ............................................... [PASS]
148/176 SpatialUpSamplingBilinear_backward_batch ........................ [PASS]
149/176 SpatialConvolutionLocal_forward_batch ........................... [PASS]
150/176 SpatialAveragePooling_forward ................................... [PASS]
151/176 Abs_forward ..................................................... [PASS]
152/176 SoftPlus_forward ................................................ [PASS]
153/176 Threshold_backward .............................................. [PASS]
154/176 SpatialAveragePooling_forward_batch ............................. [PASS]
155/176 SpatialLogSoftMax_forward ....................................... [PASS]
156/176 SpatialFullConvolution_forward_batch ............................ [PASS]
157/176 BCECriterion_forward ............................................ [PASS]
158/176 SpatialSubSampling_forward ...................................... [PASS]
159/176 SmoothL1 ........................................................ [FAIL]
160/176 SpatialAdaptiveMaxPooling_backward_noncontig .................... [PASS]
161/176 VolumetricMaxPooling_forward .................................... [PASS]
162/176 Sqrt_transposed ................................................. [PASS]
163/176 ClassNLLCriterionMultipleTargetWeights .......................... [PASS]
164/176 SpatialDilatedConvolution_forward_batch ......................... [PASS]
165/176 SpatialConvolutionMM_forward_batch .............................. [PASS]
166/176 l1cost .......................................................... [FAIL]
167/176 VolumetricMaxUnpooling_backward_batch ........................... [PASS]
168/176 SpatialConvolutionMM_forward_single ............................. [PASS]
169/176 VolumetricDilatedMaxPooling_forward_batch ....................... [PASS]
170/176 CMul_forward_batch .............................................. [PASS]
171/176 SpatialAveragePooling_includepad ................................ [PASS]
172/176 ELU_transposed .................................................. [PASS]
173/176 TemporalRowConvolution_forward_batch ............................ [PASS]
174/176 VolumetricAveragePooling_backward ............................... [PASS]
175/176 SpatialBatchNormalization ....................................... [PASS]
176/176 SpatialReplicationPadding_forward ............................... [PASS]
Completed 2255 asserts in 176 tests with 3 failures and 0 errors
--------------------------------------------------------------------------------
mse
error  on output with torch.CudaHalfTensor
LT failed: 1.00634765625 >= 0.03
	/rz2home/beckmanf/torch/install/share/lua/5.2/cunn/test.lua:3415: in function 'v'
	/rz2home/beckmanf/torch/install/share/lua/5.2/cunn/test.lua:5964: in function </rz2home/beckmanf/torch/install/share/lua/5.2/cunn/test.lua:5962>
--------------------------------------------------------------------------------
SmoothL1
error  on output with torch.CudaHalfTensor
LT failed: 0.57080078125 >= 0.01
	/rz2home/beckmanf/torch/install/share/lua/5.2/cunn/test.lua:3446: in function 'v'
	/rz2home/beckmanf/torch/install/share/lua/5.2/cunn/test.lua:5964: in function </rz2home/beckmanf/torch/install/share/lua/5.2/cunn/test.lua:5962>
--------------------------------------------------------------------------------
l1cost
error  on output with torch.CudaHalfTensor
LT failed: 0.09234619140625 >= 0.0101
	/rz2home/beckmanf/torch/install/share/lua/5.2/cunn/test.lua:4277: in function 'v'
	/rz2home/beckmanf/torch/install/share/lua/5.2/cunn/test.lua:5964: in function </rz2home/beckmanf/torch/install/share/lua/5.2/cunn/test.lua:5962>
--------------------------------------------------------------------------------
...me/beckmanf/torch/install/share/lua/5.2/torch/Tester.lua:361: An error was found while running tests!	
beckmanf@breakout:~/cunn$ 
```

So the tests **mse, SmoothL1 and l1cost** fail probably due to precision problems.

**Comment by fredowski** [comment]
@pavanky Do you see the same test failures for **mse, SmoothL1 and l1cost**?

**Comment by pavanky** [comment]
@fredowski yes.

**Comment by csxmli2016** [comment]
I also meet the same problem like @fredowski

**Comment by ortejavi** [comment]
Hi

Same problem with this configuration:

TITAN X (Pascal)
Nvidia driver: 367.48
cuda toolkit: 8.0.44
cudnn   scm-1 (installed) - /soft/torch/install/lib/luarocks/rocks

running tests, ended with 3 failures
th -lcunn -e "nn.testcuda()"
...
...
Completed 1991 asserts in 182 tests with 3 failures and 0 errors
--------------------------------------------------------------------------------
l1cost
error  on output with torch.CudaHalfTensor
LT failed: 0.11309814453125 >= 0.0101
	/soft/torch/install/share/lua/5.1/cunn/test.lua:4453: in function 'v'
	/soft/torch/install/share/lua/5.1/cunn/test.lua:6140: in function </soft/torch/install/share/lua/5.1/cunn/test.lua:6138>
--------------------------------------------------------------------------------
mse
error  on output with torch.CudaHalfTensor
LT failed: 1.8974609375 >= 0.03
	/soft/torch/install/share/lua/5.1/cunn/test.lua:3591: in function 'v'
	/soft/torch/install/share/lua/5.1/cunn/test.lua:6140: in function </soft/torch/install/share/lua/5.1/cunn/test.lua:6138>
--------------------------------------------------------------------------------
SmoothL1
error  on output with torch.CudaHalfTensor
LT failed: 0.526123046875 >= 0.01
	/soft/torch/install/share/lua/5.1/cunn/test.lua:3622: in function 'v'
	/soft/torch/install/share/lua/5.1/cunn/test.lua:6140: in function </soft/torch/install/share/lua/5.1/cunn/test.lua:6138>

**Pull request merged**
