### PR TITLE
Revert "Convert real to accreal in libTHCUNN"

### PR DESCRIPTION
**Pull request by soumith**
Reverts torch/cunn#416

### CODE REVIEW

**Comment by soumith** [comment]
i'm backing this out, it seems to be the PR responsible for almost ALL cunn tests failing with massive precision errors.

Test log here: https://gist.github.com/anonymous/85b55c2ac75e3cf51c7a4697c035d792

Tested on two separate machines with LuaJIT21, torch installed freshly via updated distro packages.

**Comment by pavanky** [comment]
@soumith FYI these are the results I ran just now on my dev machine using master before the revert:

https://gist.github.com/pavanky/0eb05fa7565403d8aa3a21e5000898d2

The only failures are 2 tests running out of memory and 2 tests failing for HalfTensors for precision issues. I got the same results before sending the PR in.

For reference, here is the setup:

- CUDA 8
- gcc-5.4
- Archlinux 64 bit
- A 2GB Maxwell mobile GPU.
- Lua 5.3

I am pretty sure the results looked similar on a Titan X the last time I ran them.

**Comment by soumith** [comment]
it's possibly something that Lua 5.3 didn't catch, and LuaJIT21 caught.
Its pretty weird, I was surprised myself.

**Comment by pavanky** [comment]
@soumith Did you notice it failing with other versions ?

**Comment by soumith** [comment]
i haven't run it with other versions. LuaJIT21 is our default version that the users installed, so was making sure that it runs.

i'll now try it for Lua5.2 as well, lets see what's up.

**Comment by deepcoord** [comment]
When I tested with LUA52, I still got errors almost all tests.

> $ th -lcunn -e 'nn.testcuda()'
> not found: THNN_CudaHalfELU_updateOutput/work/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type
> _(omitted)_
> not found: THNN_CudaHalfVolumetricFullConvolution_accGradParameters/work/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type
> seed: 	477340862	
> Running 170 tests
>   1/170 VolumetricMaxUnpooling_forward_batch ............................ [ERROR]
>   2/170 VolumetricDilatedMaxPooling_forward_batch ....................... [ERROR]
>   3/170 CMul_forward_batch .............................................. [PASS]
>   4/170 TemporalConvolution_backward_batch .............................. [ERROR]
>   5/170 VolumetricDilatedConvolution .................................... [ERROR]
>   6/170 ELU_forward ..................................................... [ERROR]
>   7/170 Sigmoid_transposed .............................................. [ERROR]
>   8/170 TemporalConvolution_forward ..................................... [ERROR]
>   9/170 SpatialFullConvolution_backward_single .......................... [ERROR]
>  10/170 Abs_backward .................................................... [ERROR]
>  11/170 TemporalConvolution_forward_batch ............................... [ERROR]

**Comment by pavanky** [comment]
@soumith @deepcoord CUDA versions and GPUs ?

**Comment by deepcoord** [comment]
@pavanky  Nvidia 367.57 and Cuda 8.0.44 on Ubuntu 16.04

**Comment by pavanky** [comment]
Hmm. I'll try replicating it.

**Comment by pavanky** [comment]
@deepcoord @soumith 

I just ran the tests with luajit21 installed from https://github.com/torch/luajit-rocks

```
 $ `which luajit` -v
LuaJIT 2.1.0-beta1 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/

 _____              _     
|_   _|            | |    
  | | ___  _ __ ___| |__  
  | |/ _ \| '__/ __| '_ \ 
  | | (_) | | | (__| | | |
  \_/\___/|_|  \___|_| |_|

 $ which lua
 $ which th
/home/pyalamanchili/Workspace/torch/local/bin//th

$ grep lua `which th`
exec '/home/pyalamanchili/Workspace/torch/local/bin/luajit' -e 'package.path="/home/pyalamanchili/.luarocks/share/lua/5.1/?.lua;/home/pyalamanchili/.luarocks/share/lua/5.1/?/init.lua;/home/pyalamanchili/Workspace/torch/local/share/lua/5.1/?.lua;/home/pyalamanchili/Workspace/torch/local/share/lua/5.1/?/init.lua;"..package.path; package.cpath="/home/pyalamanchili/.luarocks/lib/lua/5.1/?.so;/home/pyalamanchili/Workspace/torch/local/lib/lua/5.1/?.so;"..package.cpath' -e 'local k,l,_=pcall(require,"luarocks.loader") _=k and l.add_context("trepl","scm-1")' '/home/pyalamanchili/Workspace/torch/local/lib/luarocks/rocks/trepl/scm-1/bin/th' "$@"
```

I reverted this revert so it should be using my changes. Almost all tests are passing except for a few tests failing with precision errors for HalfTensors: https://gist.github.com/pavanky/582f9e24f15724552562e46eb2560dab

I ran this on Ubuntu 16.04, CUDA 8.0.44, Driver 367.57, GPU: GTX Titan Z.

Anything else I can do to reproduce this?

**Comment by pavanky** [comment]
Same with lua 5.2
```
 $ lua -v
Lua 5.2.3  Copyright (C) 1994-2013 Lua.org, PUC-Rio
 $ which luarocks
/home/pyalamanchili/Workspace/torch/local/bin//luarocks
 $ grep lua `which th`
exec '/home/pyalamanchili/Workspace/torch/local/bin/lua' -e 'package.path="/home/pyalamanchili/.luarocks/share/lua/5.2/?.lua;/home/pyalamanchili/.luarocks/share/lua/5.2/?/init.lua;/home/pyalamanchili/Workspace/torch/local/share/lua/5.2/?.lua;/home/pyalamanchili/Workspace/torch/local/share/lua/5.2/?/init.lua;"..package.path; package.cpath="/home/pyalamanchili/.luarocks/lib/lua/5.2/?.so;/home/pyalamanchili/Workspace/torch/local/lib/lua/5.2/?.so;"..package.cpath' -e 'local k,l,_=pcall(require,"luarocks.loader") _=k and l.add_context("trepl","scm-1")' '/home/pyalamanchili/Workspace/torch/local/lib/luarocks/rocks/trepl/scm-1/bin/th' "$@"
```

Test results: https://gist.github.com/pavanky/582f9e24f15724552562e46eb2560dab#file-lua52_test_results-md

Same OS, GPU setup as above.

**Pull request merged**
