### PR TITLE
Added weight support to ClassNLLCriterion

### PR DESCRIPTION
**Pull request by jonathantompson**

### CODE REVIEW

**Comment by jonathantompson** [comment]
<ping>

It would be nice to get this merged at some point.  I assume @soumith is just overworked and hasn't had time to look at it yet :-)

**Comment by szagoruyko** [comment]
how is it different from https://github.com/torch/cunn/pull/75 ?

**Comment by soumith** [comment]
I didn't merge this actually because we have one incoming thats better and more efficient (both on CPU and GPU). @adamlerer is working his way through opening Pull Requests back into cutorch/cunn, one should show up in a few days.

**Comment by jonathantompson** [comment]
@szagoruyko Yeah, it looks like it's essentially the same.  I didn't see #75.

@soumith I really need one of the PRs to be merged ASAP, so we can at least get CUDA support for NLL with weights while we're waiting for your super fancy implementation.

**Comment by soumith** [comment]
ok merging, more clean and robust implementation will be pushed in separate PR.

**Comment by jonathantompson** [comment]
@soumith Thanks mate!

**Pull request merged**
