### PR TITLE
[LookupTable] Add Max-norm constraints to LookupTable

### PR DESCRIPTION
**Pull request by xianjiec**
The cuda version for the pull request in nn:
 https://github.com/torch/nn/pull/739

### CODE REVIEW

**Comment by colesbury** [comment]
This LGTM. @xianjiec how does performance with maxNorm on compare to maxNorm off?

**Comment by xianjiec** [comment]
Hey @colesbury, the performance appears to depend on the number of unique indices in the "input". When most of the rows of the "module.weight" need to be re-normed, the running time would increase significantly.

**Comment by apaszke** [comment]
I have only a small nit: how about renaming `value` to something more meaningful like `normType` or simply `p`?

**Comment by xianjiec** [comment]
Hey @apaszke, the variable name is borrowed from torch.renorm: https://github.com/torch/torch7/blob/ad65230b55b832d8e9cf49abf512b9a03f52c0ca/lib/TH/generic/THTensorMath.c#L2299

Should we use a different name here?

**Comment by apaszke** [comment]
I see. Well, I think that it would be better to break out from this convention. It's a very uninformative name.

**Comment by xianjiec** [comment]
The `value` has been changed to `normType` in this pull request and also torch/nn#739.

**Pull request merged**
